version: '3.0'

services:
  es-playground:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es-playground
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
    data01:
        driver: local

networks:
    elastic:
        driver: bridge